spring.application.name=techcortex-backend
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/techcortex_db
spring.datasource.username=postgres
spring.datasource.password=pass@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CORS
logging.level.org.springframework.web=INFO
